### ISSUE TITLE
Copyright issue in license

### ISSUE THREAD

**Issue by akien-mga** [etmaifo/Humanoids#1]
It looks like you used the license of @vnen's tiled importer addon but forgot to change the copyright: https://github.com/etmaifo/Humanoids/blob/master/LICENSE

The name should be yours, not @vnen's ;)

**Comment by etmaifo** [comment]
The license file has been removed. The Readme file already has the license type. Thanks for spotting this.

**Comment by akien-mga** [comment]
Please readd it, a statement in the README is not enough to explicit define a license. See https://choosealicense.com/licenses/mit/

**Comment by etmaifo** [comment]
Proper license added.
